# Base image for Airflow
FROM apache/airflow:2.7.2

# Install all necessary providers, including InfluxDB
RUN pip install \
    apache-airflow-providers-postgres==5.0.0 \
    apache-airflow-providers-apache-spark==3.0.0 \
    apache-airflow-providers-influxdb==2.1.0 \
    kafka-python \
    faker \
    watchdog 

RUN mkdir -p /opt/airflow/data/reference && chmod -R 777 /opt/airflow/data/reference
